{{- $ubuntu := .Values.ubuntu }}
{{- range $i := until ($ubuntu.count | int) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-{{ add $i 1 }}
  namespace: guacamole
  labels:
    {{- include "guacamole-app.labels" $ | nindent 4 }}
spec:
  replicas: {{ $ubuntu.replicas }}
  selector:
    matchLabels:
      app: ubuntu-{{ add $i 1 }}
  template:
    metadata:
      labels:
        app: ubuntu-{{ add $i 1 }}
    spec:
      containers:
      - name: ubuntu-{{ add $i 1 }}
        image: {{ $ubuntu.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ $ubuntu.sshPort }}
{{- end }}