apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: guacamole
  labels:
    {{- include "guacamole-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ubuntu.replicas }}
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: {{ .Values.ubuntu.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.ubuntu.sshPort }}
        command: ["/usr/sbin/sshd", "-D"]
