apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ssh
  namespace: guacamole
  labels:
    {{- include "guacamole-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: ubuntu
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: guacamole
    ports:
    - protocol: TCP
      port: 22