apiVersion: v1
kind: Secret
metadata:
  name: guacamole-database-credentials
  namespace: guacamole
  labels:
    {{- include "guacamole-app.labels" . | nindent 4 }}
data:
  postgres-user: {{ .Values.postgres.username | b64enc }}
  postgres-password: {{ .Values.postgres.password | b64enc }}
  postgres-hostname: {{ .Values.postgres.serviceName | b64enc }}
  postgres-port: {{ .Values.postgres.port | b64enc }}
  postgres-database: {{ .Values.postgres.database | b64enc }}
type: Opaque