apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "guacamole-app.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: guacamole-app
    meta.helm.sh/release-namespace: guacamole
  name: postgres-secret
  namespace: guacamole
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc }}