apiVersion: v1
kind: Service
metadata:
  name: ubuntu
  namespace: guacamole
  labels:
    {{- include "guacamole-app.labels" . | nindent 4 }}
spec:
  selector:
    app: ubuntu
  ports:
  - protocol: TCP
    port: {{ .Values.ubuntu.sshPort }}
