apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "guacamole-app.labels" . | nindent 4 }}
  name: guacamole
  namespace: guacamole
spec:
  selector:
    app: guacamole
  ports:
  - name: guacamole-web
    protocol: TCP
    port: {{ .Values.guacamole.servicePort }}
    targetPort: {{ .Values.guacamole.servicePort }}
  - name: guacd
    protocol: TCP
    port: 4822
    targetPort: 4822
