{{- $ubuntu := .Values.ubuntu }}
{{- range $i := until ($ubuntu.count | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-{{ add $i 1 }}
  namespace: guacamole
  labels:
    {{- include "guacamole-app.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: ubuntu-{{ add $i 1 }}
  ports:
  - protocol: TCP
    port: {{ $ubuntu.sshPort }}
    targetPort: {{ $ubuntu.sshPort }}
{{- end }}