apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "guacamole-app.labels" . | nindent 4 }}
  name: postgres
  namespace: guacamole
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
