- hosts: all
  become: true
  tasks:
    - name: Install packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Download Kubernetes GPG key securely
      ansible.builtin.shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Kubernetes
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
      when: ansible_os_family == "Debian"
#- hosts: master
#  become: true
#  tasks:
#    - name: Kubernetes cluster init
#      command: kubeadm init --pod-network-cidr=192.168.0.0/16
#      register: kubeadm_output
#      ignore_errors: true
#
#    - name: Configure kubectl
#      command: "{{ item }}"
#      with_items:
#        - mkdir -p $HOME/.kube
#        - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#        - chown $(id -u):$(id -g) $HOME/.kube/config
#
#    - name: Configure Flannel
#      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel.yml
#
#- hosts: workers
#  become: true
#  tasks:
#    - name: Connect to master
#      command: "{{ hostvars['master'].kubeadm_output.stdout_lines[-1] }}"
